export const provinces = [
    {
        id: 1,
        province: "ALIMOSHO PROVINCE",
        chairman: "Apostle Dr James Olulaja Iyanda",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 2,
        province: "SURULERE PROVINCE",
        chairman: "Rev Ephraim Ifionu",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 3,
        province: "APAPA PROVINCE",
        chairman: "Apostle Nelson Chukwudi Eke Okpara ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 4,
        province: "OJO PROVINCE",
        chairman: "Rev Adeleke Mike Aderinto",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 5,
        province: "LAGOS ISLAND PROVINCE",
        chairman: "Rev. Tony Samson",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 6,
        province: "BADAGRY PROVINCE",
        chairman: "Bishop John Oyedeji Seton Benhotons ",
        Secretariat: 'Divine Spring Ministries, Omi-Eye Street, Ibereko, Badagry, Lagos.',
        MeetingDays: "Last Friday of The Month",
    },
    {
        id: 7,
        province: "IBEJU/LEKKI PROVINCE ",
        chairman: "Rev Dr Andrew Isiaka Oladepo",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 8,
        province: "IKEJA PROVINCE",
        chairman: "Pastor Tope ILESANMI",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 9,
        province: "IKORODU PROVINCE",
        chairman: "Commander Peter Olabode ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 10,
        province: "ETIOSA PROVINCE ",
        chairman: "BISHOP FEMI SONEYE ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 11,
        province: "AMUWO ODOFIN/ORIADE PROVINCE ",
        chairman: "APOSTLE PATRICK UTULU ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 12,
        province: "ITAMAGA PROVINCE",
        chairman: "Apostle M. A. Olugbaro ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 13,
        province: "AGEGE PROVINCE",
        chairman: "Bishop Dr Praise Oliver",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 14,
        province: "KOSOFE PROVINCE ",
        chairman: "Apostle Dr. Joshua Olaoye ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 15,
        province: "AGBADO OKE ODO PROVINCE",
        chairman: "Pastor (Barr.) Samuel O. Afilaka ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 16,
        province: "IFAKO IJAIYE PROVINCE ",
        chairman: "Rev Alfred Olatunde Shoyemi ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 17,
        province: "AYOBO/OKUNOLA PROVINCE",
        chairman: "Bishop Samuel Oludare Oladiti",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 18,
        province: "MAINLAND PROVINCE",
        chairman: "Rev S.T Israel ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 19,
        province: "EPE PROVINCE ",
        chairman: "Rev Aghraghra Victor Uzezi ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 20,
        province: "ISOLO EJIGBO PROVINCE ",
        chairman: "Apostle George Anselem ",
        Secretariat: '',
        MeetingDays: "",
    },
    {
        id: 21,
        province: "MUSHIN OSHODI ",
        chairman: "Apostle Okechukwu Etiaka",
        Secretariat: '',
        MeetingDays: "",
    },
]