import Img from '../images/pro3.jpg'
export const cwc = [
  {
    id: 1,
    img: Img,
    name: "APOSTLE ENYINNAYA OKWUONU",
    church: "New Life Christian Church",
    address: "97c, Marine Road, Apapa GRA",
    tel: "08023355366, 07061000181",
    dOb: "30th March",
    email: "enyinnaya56@yahoo.com",
    chapter: "Apapa",
    province: "Apapa/Surulere",
  },
  {
    id: 2,
    img: Img,
    name: "PASTOR LEKE AKINOLA",
    church: "Upper Room Baptist Church",
    address: "20, Davies Street, Off Demurin Street, Ketu Lagos",
    tel: "08035652137, 08057845480",
    dOb: "2nd February",
    email: "lekeakinola@yahoo.co.uk",
    chapter: "Ketu Central",
    province: "Kosofe",
  },
  {
    id: 3,
    img: Img,
    name: "APOSTLE AKINYELE AKINDEJOYE",
    church: "Guiding Light Assembly",
    address:
      "Epe Blk 2, Plot 5, Atowa Adegoke Street, Agric Estate, Papa-Epe, Lagos.",
    tel: "08033212772, 09055514094",
    dOb: "9th March",
    email: "dejoye@gmail.com Pastorakinz2@yahoo.com",
    chapter: "Papa-Epe",
    province: "EPE",
    associatePastorTel: "08034202048",
  },
  {
    id: 4,
    img: Img,
    name: "REV (DR) PEACE GOODEY",
    church: "Christ Believers Healing Ministries AKA Christ Believers Assembly",
    address: "",
    headOffice:
      "Truth And Holiness Parish Oluwakemi Close(Street by Access Bank) off Addo Road, Ajah.",
    tel: "08057797482, 08023187035",
    dOb: "27th November",
    email: "goodeypeace@yahoo.com",
    chapter: "",
    province: "",
    associatePastor: "Pastor (Barrister) Udom Udom",
    associatePastorTel: "08035230642",
    associatePastorChapter: "Ajah",
    associatePastorProvince: "Eti/Osa",
  },
  {
    id: 5,
    img: Img,
    name: "PASTOR BAYO OYEYEMI",
    church: "Deeper Christian Life Ministries",
    address: "",
    headOffice: "",
    tel: "08023213789, +234 815 090 1500",
    dOb: "",
    email: "",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 6,
    img: Img,
    name: "Rev. Juliet Biniti",
    church: "Precious Jewel Ministries International",
    address: "",
    headOffice: "",
    tel: "+234 805 799 0930",
    dOb: "June 4",
    email: "revjulietbinitie@gmail.com",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 7,
    img: Img,
    name: "REV FRANK ERHABOR ",
    church: "Good Success Christian Center",
    address: "6, Tologbo Road Magbon Badagry",
    headOffice: "",
    tel: "08033324470",
    dOb: " 6th July",
    email: "revjulietbinitie@gmail.com",
    chapter: "",
    province: "Badagry",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 8,
    img: Img,
    name: "REV. OLUSANYA FOLAHAN OLUMUYIWA ",
    church: "The Living Stone Builders Ministries",
    address:
      "56/58, Lambo Lasunwon Road, Opp Lagos State Poly, 1st Gate, Shagamu Rd, Ikorodu",
    headOffice: "",
    tel: "08023375174",
    dOb: " 6th February ",
    email: "folahanolusanya@yahoo.com ",
    chapter: "Jubilee",
    province: "Ikorodu ",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 9,
    img: Img,
    name: "Apostle Tonye Oliver ",
    church: "Jesus Heals the Sick Ministries",
    address: "951, Admiral Oduwaiye St Omole Phase 2",
    headOffice: "",
    tel: "08933919496",
    dOb: " December 13 ",
    email: "tonyeoliver5@gmail.com pastortonye@jesushealsthesick.org",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 10,
    img: Img,
    name: "Rev. Mrs Roseline Odiete ",
    church: "Christ Peculiar Church Int",
    address: "33b Ibafon street behind Zenith Bank  Oshodi Apapa Express way",
    headOffice: "",
    tel: "+234 803 064 5565",
    dOb: " January ",
    email: "odieteroseline43@gmail.com",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 11,
    img: Img,
    name: "REV (MRS) GLORY AKPABIO ",
    church: "Christ Chapel International Church, Surulere",
    address: "",
    headOffice: "",
    tel: "08032234656",
    dOb: "  23rd February ",
    email: "glakia@yahoo.com ",
    chapter: "Kilo/Ikate",
    province: "Apapa/Suruler",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 12,
    img: Img,
    name: "PASTOR CLEM IWEGBU ",
    church: "The Redeemed Evangelical Mission",
    address: "TREM NATIONAL HQTRS/OKOTA ISOLO",
    headOffice: "",
    tel: "08023152389",
    dOb: "  30th August ",
    email: " rev.clemiwegbu@yahoo.com  ",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 13,
    img: Img,
    name: "BARRISTER TOMI VINCENT ",
    church: "Ivory Solicitors",
    address: "374, Ikorodu Road, Maryland. Lagos ",
    headOffice: "",
    tel: "08033026306, 08037122564",
    dOb: "  18th May",
    email: "  tomivincent@yahoo.com   ",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 14,
    img: Img,
    name: "Enushai Sylvester Success Ngozi  ",
    church: "Mountain of fire and miracles ministries",
    address: "13 Olasimbo street  Yaba Lagos ",
    headOffice: "",
    tel: "08037116342",
    dOb: "April 16",
    email: "  enushaisylvester1234@gmail.com   ",
    chapter: "Iwaya chapter",
    province: "Mainland province",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 15,
    img: Img,
    name: "BISHOP MATTHEW EGWUOWA  ",
    church: "Church of God Mission ",
    address: "N0. 10, Oludegu avenue, Mafoluku,off Airport road ",
    headOffice: "",
    tel: "+234 803 327 4311 ",
    dOb: " 01/10 ",
    email: "  egwowamatthew@gmail.com   ",
    chapter: "waya chapter",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 16,
    img: Img,
    name: "Pastor S. A. Lebi   ",
    church: " ",
    address: " ",
    headOffice: "",
    tel: "+234 803 395 0888 ",
    dOb: " ",
    email: " ",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 17,
    img: Img,
    name: "Evang. Chris Joseph",
    church: "The Lord's Chosen Charismatic Revival Movement",
    address: "10 Odofin Park Estate, Oshodi Apapa Express Way by Ijesha Bus-stop, Lagos",
    headOffice: "",
    tel: "08060231959, 07069426060",
    dOb: "28/10 ",
    email: "chris.mlpwo@gmail.com",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
  {
    id: 18,
    img: Img,
    name: "BOSE OLASUPO ",
    church: "Guiding Light Assembly",
    address: "Layi Ajayi-Bembe Rd, Parkview Estate, Ikoyi ",
    headOffice: "",
    tel: " 08034961055",
    dOb: " 5th April ",
    email: " Ennywealt4real@yahoo.com ",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: "",
  },
];

// The Directors
export const directors = [
    {
        id: 1,
        img: Img,
        name: "PASTOR OLUMIDE OLUGBENLE",
        church: "The Father's House, Rehoboth International Christian Centre",
        address: "62, Bamidele Eletu Avenue, Osapa-London, Lekki.",
        headOffice: "",
        tel: "08036586433",
        dOb: "3rd June",
        email: "olumideolugbenle@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 2,
        img: Img,
        name: "Bishop Dr. Theophilus Taiwo Ajose.",
        church: "Bishop Ajose Ministries International.",
        address: "17B Adekunbi Crescent Off Allen Avenue off Ladipo Kasumu street, Ikeja, Lagos.",
        headOffice: "",
        dOb: "May 31st",
        tel: "",
        email: "bishopajoseministries@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 3,
        img: Img,
        name: "PASTOR CHIGOZIE ANYANWU",
        church: "Zion The City of The Lord Ministries",
        address: "11, Eko Akete Close, Off St. Greggory's College Rd, Obalende, Lagos",
        headOffice: "",
        dOb: "24th February",
        tel: "07040909240, 07030505092",
        email: "chiggywise@yahoo.com",
        chapter: "Obalende",
        province: "Island/Eti-Osa",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 4,
        img: Img,
        name: "Evangelist Olalekan Amusan",
        church: "Christ Image Assembly",
        address: "27 Carter Street Ebute Metta Lagos",
        headOffice: "",
        dOb: "August 3rd",
        tel: "08023468777",
        email: "lekanonmission@yahoo.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 5,
        img: Img,
        name: "Pastor Obinna Paul Egbuonu",
        church: "The *Haven Rock Church",
        address: "28 Omotayo Banwo Street Ogudu Orioke Ogudu Lagos",
        headOffice: "",
        dOb: "8th January",
        tel: "09012652206",
        email: "obimsema75@gmail.com",
        chapter: "",
        province: "Ikeja Central",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 6,
        img: Img,
        name: "APOSTLE MIKE HONOUR AKINYOADE",
        church: "The Royalty Place",
        address: "3, Church Street, Odo-Eran Ekore Bus-Stop, Oworoshoki, Lagos",
        headOffice: "",
        dOb: "22nd August",
        tel: "08038518769, 08153287478, 08107684912",
        email: "apostleakinyoade@gmail.com; theroyaltyplacetrp@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 7,
        img: Img,
        name: "Apostle Dr Benjamin Omoregie Osagie",
        church: "Rehoboth Church of Christ Ambassadors Worldwide",
        address: "No 5, Rehoboth Street, Alakun Off BABA-ADISA Road, Ibeju Lekki, Lagos",
        headOffice: "",
        dOb: "16/03/1966",
        tel: "08023081292",
        email: "apostlebenomoregie@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 8,
        img: Img,
        name: "BISHOP MOSES. A. IDRIS",
        church: "MINISTRY NAME: LIVING ROCK GOSPEL CHURCH INT'L",
        address: "1/3 TINUADE ADEPEGBA STREET OFF ADEPEGBA ROAD, ABULE EGBA LAGOS.",
        headOffice: "",
        dOb: "10TH MARCH",
        tel: "08022232704; 0905 579 0517",
        email: "livingrockgospel@yahoo.com",
        chapter: "Abule Egba",
        province: "Ifako/Ijaiye",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 9,
        img: Img,
        name: "Rev Dr David Austin Osayi",
        church: "The Reigning Christian Church",
        address: "12 Ajimson Street, waterside Ojo Volks",
        headOffice: "",
        dOb: "22nd May",
        tel: "07034533799, 08070652674",
        email: "davidosayiaustin@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 10,
        img: Img,
        name: "PASTOR (DR) OLUMUYIWA ADEDOYIN OLULANA",
        church: "Glorious Destiny Church",
        address: "4,Cecilia Odutuga Street, Ilasamaja, Lagos",
        headOffice: "",
        dOb: "10th September",
        tel: "08033123225, 08120070680",
        email: "oluolulana54@gmail.com",
        chapter: "Ilasamaja",
        province: "Isolo/Mushin",
        associatePastor: "Pastor Mrs. M. O. Olulana",
        associatePastorTel: "08033185708",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 11,
        img: Img,
        name: "REV. OLADELE AFOLABI",
        church: "Christ Base Assembly",
        address: "10 Shokoya Street Oworonsoki",
        headOffice: "",
        tel: "08034876621",
        email: "oladele.afolabi@ymail.com",
        dOb: "18th June",
        chapter: "Ilasamaja",
        province: "Kosofe",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 12,
        img: Img,
        name: "REV.DR. MOSES BABATUNDE ELEBUTE",
        church: "International Christian Faith Mission",
        address: "14, Aina Close, New Garage, Gbagada, Lagos.",
        headOffice: "",
        tel: "08023159130",
        email: "moseselebute58@gmail.com",
        dOb: "December 4th",
        chapter: "Ilasamaja",
        province: "Kosofe",
        associatePastor: "Pastor (Mrs) Toyin Elebute",
        associatePastorTel: "08053077798",
        associatePastorChapter: "Gbagada",
        associatePastorProvince: "Mainland"
    },
    {
        id: 13,
        img: Img,
        name: "PASTOR DR. BARNABAS OTOIBHI.",
        church: "Temple Rebuilders Ministry.",
        address: "5, Aimasiko Street, Off Afariogun Street, By Charity Bus-Stop, Oshodi, Lagos",
        headOffice: "",
        tel: "08033136167, 08125720158",
        email: "barnytessy@yahoo.com",
        dOb: "15/12",
        chapter: "Oshodi",
        province: "Mushin/Oshodi",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 14,
        img: Img,
        name: "PASTOR DR. BARNABAS OTOIBHI.",
        church: "Temple Rebuilders Ministry.",
        address: "5, Aimasiko Street, Off Afariogun Street, By Charity Bus-Stop, Oshodi, Lagos",
        headOffice: "",
        tel: "08033136167, 08125720158",
        email: "barnytessy@yahoo.com",
        dOb: "15/12",
        chapter: "Oshodi",
        province: "Mushin/Oshodi",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 15,
        img: Img,
        name: "BISHOP ANDY OGBU",
        church: "Dominion Life Centre",
        address: "18, Ebun Otti Street off Frank Lass Bus stop Opp. Lagos State University, Ojo, Badagry Exp.",
        headOffice: "",
        tel: "08033122772, 08120870163",
        email: "dominionlife@gmail.com",
        dOb: "23rd November",
        chapter: "Ojo",
        province: "Ojo",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 16,
        img: Img,
        name: "APOSTLE KEN CHIDUBEM",
        church: "World Lighters Ministries",
        address: "2 Ecwa church road by Alafia bus stop, Coker Orile Iganmu Lagos.",
        headOffice: "",
        tel: "07064691511",
        email: "Kengivethemlight@gmail.com",
        dOb: "18/12",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 17,
        img: Img,
        name: "Pastor David Oluwatosin Oladipupo",
        church: "CommunionHouse",
        address: "3rd Avenue Gowon Estate, Egbeda",
        headOffice: "",
        tel: "08100675902",
        email: "tsn_oladipupo@yahoo.com",
        dOb: "02 August",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 17,
        img: Img,
        name: "Apostle Dr Ameh Joseph Sunday.",
        church: "Restoration Royal Mega Church.",
        address: "15/16, Mohammed Adah Street, Gojere Town, Opposite Ojo Barracks. Ojo Lagos.",
        headOffice: "",
        tel: "08033000758. 08154146579.",
        email: "doctorameh@gmail.com",
        dOb: "",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 18,
        img: Img,
        name: "Rev .Dr Dele Ajayi",
        church: "Chapel of Christ The Light",
        address: "1,CIPM ROAD, CBD, ALAUSA, IKEJA",
        headOffice: "",
        tel: "08023269835",
        email: "oladeleajayi83@gmail.com",
        dOb: "13th January",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 19,
        img: Img,
        name: "Rev .Dr Dele Ajayi",
        church: "Chapel of Christ The Light",
        address: "1,CIPM ROAD, CBD, ALAUSA, IKEJA",
        headOffice: "",
        tel: "08023269835",
        email: "oladeleajayi83@gmail.com",
        dOb: "13th January",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 20,
        img: Img,
        name: "APOSTLE CLEMS PREACHER AKIBOR",
        church: "Jubilee Family Christian Church int'l.",
        address: "40/41 Sule Descendants way, off Church bustop, Okoko Lagos.",
        headOffice: "",
        tel: "08034028313",
        email: "clemspreacher@gmail.com",
        dOb: "February 12th",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 21,
        img: Img,
        name: "Mrs Helen Karika",
        church: "Upper Room Baptist Church",
        address: "Vina Street, Off Badore Road Badore, Ajah, Lekki Lagos.",
        headOffice: "",
        tel: "08023285245",
        email: "helenkarika@yahoo.com",
        dOb: "February 12",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 22,
        img: Img,
        name: "Rev Dr Eric IGHALO",
        church: "Changemakers Africa Youth Empowerment Initiative.",
        address: "142,Oba Akran Road .4th floor,Poatson House.Suite 4.Ikeja.Lagos.",
        headOffice: "",
        tel: "08023291520(main line) 09092218683",
        email: "changemakersafrica@gmail.com, ericandpartners@gmail.com",
        dOb: "19th Dec.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 23,
        img: Img,
        name: "Rev Dr Eric IGHALO",
        church: "Changemakers Africa Youth Empowerment Initiative.",
        address: "142,Oba Akran Road .4th floor,Poatson House.Suite 4.Ikeja.Lagos.",
        headOffice: "",
        tel: "08023291520(main line) 09092218683",
        email: "changemakersafrica@gmail.com, ericandpartners@gmail.com",
        dOb: "19th Dec.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 24,
        img: Img,
        name: "BISHOP ( DR ) JOY OBERIKO",
        church: "DIVINE SOULS FOR CHRIST CHURCH INTERNATIONAL ( BELIEVERS CATHEDRAL)",
        address: "NO 3 LUQMON AVENUE AHMADIYA LAGOS STATE.",
        headOffice: "",
        tel: "08023428133",
        email: "bishopjoyoberiko2012@gmail.com",
        dOb: "DECEMBER 25TH",
        chapter: "Ojokoro",
        province: "Ifako/Ijaiye",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 25,
        img: Img,
        name: "Pastor Emmanuel Olu Falodun",
        church: "Christ Salvation Victory Mission Int'l",
        address: "63, Falohun Street, Orile Iganmu, Lagos",
        headOffice: "",
        tel: "08033337793",
        email: "powerforexploits@gmail.com",
        dOb: "May 17",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 26,
        img: Img,
        name: "APOSTLE IDONG JAMES",
        church: "ALIVE TABERNACLE INT'L",
        address: "APOSTLE IDONG JAMES ALIVE TABERNACLE INT'L NO.9 IREPODUN STREET OFF ARIGBANLA ROAD, BEHIND NYSC ORIENTATION CAMP MURELO ABEKOKO BUSTOP, ORILE AGEGE L.G.AREA IYANA IPAJA, LAGOS",
        headOffice: "",
        tel: "08054449444/08033393359",
        email: "",
        dOb: "",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 27,
        img: Img,
        name: "REV. DR. AKINLADE",
        church: "",
        address: "",
        headOffice: "",
        tel: "+234 909 170 3599",
        email: "",
        dOb: "",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 28,
        img: Img,
        name: "Apostle Stephen Atolani Pius",
        church: "FIRST ESTATE WORLD OUTREACH MINISTRY INC.",
        address: "EDEN CHAPEL LAOGS, KM 5 LASU - Isheri Expressway College Bus Stop, Mojeed Sanni Street Igando Lagos.",
        headOffice: "",
        tel: "08033333854; 09096965179",
        email: "pastsong@yahoo.com, edenchapel42@gmail.com",
        dOb: "15th Jan",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 29,
        img: Img,
        name: "BISHOP MATTHEW EGWUOWA",
        church: "Church of God Mission",
        address: "N0. 10, Oludegu avenue, Mafoluku,off Airport road.",
        headOffice: "",
        tel: "+234 803 327 4311",
        email: "egwowamatthew@gmail.com",
        dOb: "01/10",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 30,
        img: Img,
        name: "Barr. (Mrs.) Tina Oganiru",
        church: "CPM Okota Branch",
        address: "",
        headOffice: "",
        tel: "0802 315 1022",
        email: "a_oganirulaw@yahoo.com",
        dOb: "3rd August",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
]

//The Chairmen
export const chairmen = [
    {
        id: 1,
        img: Img,
        name: "Apostle Dr James Olulaja Iyanda",
        church: "Go Ye Pentecostal Mission International",
        address: "55 alimoso road pako bus stop LG Lagos",
        headOffice: "",
        tel: "08060582967. 08023407924",
        email: "olulajaiyanda2016@gmail.com",
        dOb: "June 3rd",
        chapter: "",
        province: "",
        associatePastor: "Rev. Mrs. Temi -James Iyanda",
        associatePastorTel: "07064680302",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 2,
        img: Img,
        name: "REV EPHRAIM IFIONU",
        church: "Glory Restoration Ministries International",
        address: "30 Coker Road Orile Iganmu, Lagos.",
        headOffice: "",
        tel: "08033331066, 08097362066",
        email: "ephraimifionu@gmail.com",
        dOb: "13th December",
        chapter: "",
        province: "Surulere",
        associatePastor: "Rev. Mrs. Temi -James Iyanda",
        associatePastorTel: "07064680302",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 3,
        img: Img,
        name: "APOSTLE NELSON CHUKWUDI EKE OKPARA",
        church: "Sowers' International Ministry",
        address: "6 Akaka Lane, off DadaOnijomoh Crescent, behinds Berger yard, Otto Wharf, Ajegunle, Apapa.",
        headOffice: "",
        tel: "09054562000",
        email: "bishopinsowers@gmail.com",
        dOb: "07 September.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 4,
        img: Img,
        name: "Rev Adeleke Mike Aderinto",
        church: "Life Transforming Evangelical Church.",
        address: "34 Kareem Street Shibiri",
        headOffice: "",
        tel: "08023588405",
        email: "mikeadeleke77@gmail.com",
        dOb: "16/12",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 5,
        img: Img,
        name: "Rev. Tony Samson",
        church: "TREM (The Redeemed Evangelical Mission )",
        address: "20 Remi Olowude way Off Marwa Bus Stop Lekki, Lagos",
        headOffice: "",
        tel: "+2348033562990",
        email: "tonysamson135@gmail.com",
        dOb: "02/09",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 6,
        img: Img,
        name: "Bishop John Oyedeji Seton Benhotons",
        church: "Didasko Global Mission/Reigning Word Fountain Church Association Avenue, Ibereko",
        address: "Ibereko",
        headOffice: "",
        tel: "08034951550",
        email: "johnbenhotons@yahoo.co.uk",
        dOb: "26th September",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 6,
        img: Img,
        name: "REV DR ANDREW ISIAKA OLADEPO",
        church: "SCRIPTURE LIFE CHRISTIAN CENTRE INC",
        address: "Plots 1/3 Scripture Life Way, Iya Alagbo Area Awoyaya. Ibeju Lekki Lagos.",
        headOffice: "",
        tel: "08023154453, 07043421533",
        email: "andrewoladepo4scripturelife@yahoo.com",
        dOb: "17th Oct.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 7,
        img: Img,
        name: "Pastor Tope ILESANMI",
        church: "Revival Summit Ministries",
        address: "Plot 165, Obadina street, Omole Phase 1,Ikeja L/G.",
        headOffice: "",
        tel: "08032139688, 08023007209- WhatsApp line",
        email: "pastortopesanmi@gmail.com",
        dOb: "23rd December.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 8,
        img: Img,
        name: "COMMANDER PETER OLABODE",
        church: "Moment of Grace and Fire Ministry",
        address: "2, Salvation and Praise City Close Keke Maruwa Last Bus Stop Selewu, Igbogbo Lagos",
        headOffice: "",
        tel: "08032288773",
        email: "peterolabode8@gmail.co",
        dOb: "8/9",
        chapter: "",
        province: "",
        associatePastor: "Pastor Mrs. V. O. Olabode",
        associatePastorTel: "08032288773",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 9,
        img: Img,
        name: "BISHOP FEMI SONEYE",
        church: "MIRACLEBREED ASSEMBLY",
        address: "TRAILBLAZERS CONVENTION CENTER TREASURE ESTATE AFA BUS STOP, SHANGOTEDO KM 46, LEKKI-EPE EXPRESS WAY. LAGOS",
        headOffice: "",
        tel: "08023039870",
        email: "miraclebreed_assembly@yahoo.com, femi.soneye5570@gmail.com",
        dOb: "May 5th",
        chapter: "",
        province: "",
        associatePastor: "Pastor Mrs. V. O. Olabode",
        associatePastorTel: "08032288773",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 10,
        img: Img,
        name: "APOSTLE PATRICK UTULU",
        church: "Dominion Gate Min Int'L Inc,",
        address: "No 1 Church Street, Liverpool Estate, Zone 2, Satellite Town.",
        headOffice: "",
        tel: "08033215129",
        email: "apostleUtulu@yahoo.com",
        dOb: "20th August",
        chapter: "Satellite Chapter",
        province: "Amuwo-Odofin/Oriade",
        associatePastor: "Pastor Mrs. V. O. Olabode",
        associatePastorTel: "08032288773",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 11,
        img: Img,
        name: "APOSTLE M. A. OLUGBARO",
        church: "",
        address: "",
        headOffice: "",
        tel: "08033834251",
        email: "",
        dOb: "",
        chapter: "",
        province: "Itamaga Province",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 12,
        img: Img,
        name: "Bishop Dr Praise Oliver.",
        church: "FRESH FIRE REVIVAL CHAPEL",
        address: "No. 287 Lagos Abeokuta Express Way. Pleasure bus stop. Lagos.",
        headOffice: "",
        tel: "07061121896. 08023175028",
        email: "bishoppraiseoliver@gmail.com",
        dOb: "May 12",
        chapter: "",
        province: "AGEGE OGBA PROVINCE.",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 13,
        img: Img,
        name: "Apostle.Dr.Joshua Olaoye",
        church: "TRIUMPHANT FAITH GLOBAL CHURCHES INC.",
        address: "6, OLAKUNLE STR., OWODE-AJEGUNLE, IKORODU ROAD, LAGOS.",
        headOffice: "",
        tel: "08086893567; 07055454378",
        email: "joshuatfm@yahoo.com",
        dOb: "23RD SEPT.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 14,
        img: Img,
        name: "Apostle.Dr.Joshua Olaoye",
        church: "TRIUMPHANT FAITH GLOBAL CHURCHES INC.",
        address: "6, OLAKUNLE STR., OWODE-AJEGUNLE, IKORODU ROAD, LAGOS.",
        headOffice: "",
        tel: "08086893567; 07055454378",
        email: "joshuatfm@yahoo.com",
        dOb: "23RD SEPT.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 15,
        img: Img,
        name: "Pastor (Barr.) Samuel O. Afilaka",
        church: "The Faithful Reconcilers' Bible Ministry (Reconcilers'Church)",
        address: "No. 14, Ifelodun Street, Agbelekale, Abule-Egba, Lagos State",
        headOffice: "",
        tel: "08023023038",
        email: "samafilaka@yahoo.com",
        dOb: "5th December.",
        chapter: "Agbelekale",
        province: "Agbado/Oke-Odo.",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 16,
        img: Img,
        name: "Rev Alfred Olatunde Shoyemi",
        church: "The Truth Christian Mission",
        address: "3/5 Adesola Street Off Sanni Balogun St. Abule-Egba Lagos.",
        headOffice: "",
        tel: "+234 802 283 9320",
        email: "olatundeshoyemi@yahoo.com",
        dOb: "December 3",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 17,
        img: Img,
        name: "BISHOP SAMUEL OLUDARE OLADITI",
        church: "VICTORY INTERNATIONAL FAITH MISSION",
        address: "11/13 VICTORY CLOSE OFF CANDOS ROAD BARUWA IPAJA LAGOS",
        headOffice: "",
        tel: "08023219541",
        email: "vifmlagos@yahoo.com",
        dOb: "MARCH 10TH",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 18,
        img: Img,
        name: "REV S.T ISRAEL",
        church: "CITY OF GOD RESURRECTION ASSEMBLY",
        address: "4A ADARAMAJA ST, IWAYA YABA LAGOS",
        headOffice: "",
        tel: "08179936106",
        email: "israeltosin01@gmail.com",
        dOb: "OCTOBER 20TH",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 19,
        img: Img,
        name: "Rev Aghraghra Victor Uzezi",
        church: "The Transformed Christian Assembly (Inc).",
        address: "54,kasali Oluwo St, Papa Epe Lagos State.",
        headOffice: "",
        tel: "08055805027; 08062492108",
        email: "vuaghraghra@gmail.com",
        dOb: "27/09/55",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 20,
        img: Img,
        name: "APOSTLE GEORGE ANSELEM",
        church: "GRACE LIFE ASSEMBLY",
        address: "14 APATA STREET, OPPOSITE OBA PALACE IYANA EJIGBO. LAGOS STATE", 
        headOffice: "",
        tel: "08024719223, 08038891465",
        email: "bishopgeorge_a@yahoo.com Georgeanselem@gmail.com",
        dOb: "27/09/55",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 21,
        img: Img,
        name: "APOSTLE OKECHUKWU ETIAKA.",
        church: "CORNERSTONE BIBLE BELIEVERS CHURCH INT'L",
        address: "No 18a SADIKU STREET OGUNDELE MAFOLUKU LAGOS.", 
        headOffice: "",
        tel: "07039004545 / 09071111177",
        email: "okechukwuetiaka4christ@gmail.com",
        dOb: "MARCH 3rd",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
]