import Img from '../images/splash3.jpg'
export const cwc = [{
    id: 1,
    img: Img,
    name: "APOSTLE ENYINNAYA OKWUONU",
    church: "New Life Christian Church",
    address: "97c, Marine Road, Apapa GRA",
    tel: "08023355366, 07061000181",
    dOb: "30th March",
    email: "enyinnaya56@yahoo.com",
    chapter: "Apapa",
    province: "Apapa/Surulere"

},
{
    id: 2,
    img: Img,
    name: "PASTOR LEKE AKINOLA",
    church: "Upper Room Baptist Church",
    address: "20, Davies Street, Off Demurin Street, Ketu Lagos",
    tel: "08035652137, 08057845480",
    dOb: "2nd February",
    email: "lekeakinola@yahoo.co.uk",
    chapter: "Ketu Central",
    province: "Kosofe"
},
{
    id: 3,
    img: Img,
    name: "APOSTLE AKINYELE AKINDEJOYE",
    church: "Guiding Light Assembly",
    address: "Epe Blk 2, Plot 5, Atowa Adegoke Street, Agric Estate, Papa-Epe, Lagos.",
    tel: "08033212772, 09055514094",
    dOb: "9th March",
    email: "dejoye@gmail.com Pastorakinz2@yahoo.com",
    chapter: "Papa-Epe",
    province: "EPE",
    associatePastorTel: "08034202048"
},
{
    id: 4,
    img: Img,
    name: "REV (DR) PEACE GOODEY",
    church: "Christ Believers Healing Ministries AKA Christ Believers Assembly",
    address: "",
    headOffice: "Truth And Holiness Parish Oluwakemi Close(Street by Access Bank) off Addo Road, Ajah.",
    tel: "08057797482, 08023187035",
    dOb: "27th November",
    email: "goodeypeace@yahoo.com",
    chapter: "",
    province: "",
    associatePastor: "Pastor (Barrister) Udom Udom",
    associatePastorTel: "08035230642",
    associatePastorChapter: "Ajah",
    associatePastorProvince: "Eti/Osa"
},
{
    id: 5,
    img: Img,
    name: "PASTOR BAYO OYEYEMI",
    church: "Deeper Christian Life Ministries",
    address: "",
    headOffice: "",
    tel: "08023213789, +234 815 090 1500",
    dOb: "",
    email: "",
    chapter: "",
    province: "",
    associatePastor: "",
    associatePastorTel: "",
    associatePastorChapter: "",
    associatePastorProvince: ""
},
]

// The Directors
export const directors = [
    {
        id: 1,
        img: Img,
        name: "PASTOR OLUMIDE OLUGBENLE",
        church: "The Father's House, Rehoboth International Christian Centre",
        address: "62, Bamidele Eletu Avenue, Osapa-London, Lekki.",
        headOffice: "",
        tel: "08036586433",
        dOb: "3rd June",
        email: "olumideolugbenle@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 2,
        img: Img,
        name: "Bishop Dr. Theophilus Taiwo Ajose.",
        church: "Bishop Ajose Ministries International.",
        address: "17B Adekunbi Crescent Off Allen Avenue off Ladipo Kasumu street, Ikeja, Lagos.",
        headOffice: "",
        dOb: "May 31st",
        tel: "",
        email: "bishopajoseministries@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 3,
        img: Img,
        name: "PASTOR CHIGOZIE ANYANWU",
        church: "Zion The City of The Lord Ministries",
        address: "11, Eko Akete Close, Off St. Greggory's College Rd, Obalende, Lagos",
        headOffice: "",
        dOb: "24th February",
        tel: "07040909240, 07030505092",
        email: "chiggywise@yahoo.com",
        chapter: "Obalende",
        province: "Island/Eti-Osa",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 4,
        img: Img,
        name: "Evangelist Olalekan Amusan",
        church: "Christ Image Assembly",
        address: "27 Carter Street Ebute Metta Lagos",
        headOffice: "",
        dOb: "August 3rd",
        tel: "08023468777",
        email: "lekanonmission@yahoo.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 5,
        img: Img,
        name: "Pastor Obinna Paul Egbuonu",
        church: "The *Haven Rock Church",
        address: "28 Omotayo Banwo Street Ogudu Orioke Ogudu Lagos",
        headOffice: "",
        dOb: "8th January",
        tel: "09012652206",
        email: "obimsema75@gmail.com",
        chapter: "",
        province: "Ikeja Central",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 6,
        img: Img,
        name: "APOSTLE MIKE HONOUR AKINYOADE",
        church: "The Royalty Place",
        address: "3, Church Street, Odo-Eran Ekore Bus-Stop, Oworoshoki, Lagos",
        headOffice: "",
        dOb: "22nd August",
        tel: "08038518769, 08153287478, 08107684912",
        email: "apostleakinyoade@gmail.com; theroyaltyplacetrp@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 7,
        img: Img,
        name: "Apostle Dr Benjamin Omoregie Osagie",
        church: "Rehoboth Church of Christ Ambassadors Worldwide",
        address: "No 5, Rehoboth Street, Alakun Off BABA-ADISA Road, Ibeju Lekki, Lagos",
        headOffice: "",
        dOb: "16/03/1966",
        tel: "08023081292",
        email: "apostlebenomoregie@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 8,
        img: Img,
        name: "BISHOP MOSES. A. IDRIS",
        church: "MINISTRY NAME: LIVING ROCK GOSPEL CHURCH INT'L",
        address: "1/3 TINUADE ADEPEGBA STREET OFF ADEPEGBA ROAD, ABULE EGBA LAGOS.",
        headOffice: "",
        dOb: "10TH MARCH",
        tel: "08022232704; 0905 579 0517",
        email: "livingrockgospel@yahoo.com",
        chapter: "Abule Egba",
        province: "Ifako/Ijaiye",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 9,
        img: Img,
        name: "Rev Dr David Austin Osayi",
        church: "The Reigning Christian Church",
        address: "12 Ajimson Street, waterside Ojo Volks",
        headOffice: "",
        dOb: "22nd May",
        tel: "07034533799, 08070652674",
        email: "davidosayiaustin@gmail.com",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 10,
        img: Img,
        name: "PASTOR (DR) OLUMUYIWA ADEDOYIN OLULANA",
        church: "Glorious Destiny Church",
        address: "4,Cecilia Odutuga Street, Ilasamaja, Lagos",
        headOffice: "",
        dOb: "10th September",
        tel: "08033123225, 08120070680",
        email: "oluolulana54@gmail.com",
        chapter: "Ilasamaja",
        province: "Isolo/Mushin",
        associatePastor: "Pastor Mrs. M. O. Olulana",
        associatePastorTel: "08033185708",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 11,
        img: Img,
        name: "REV. OLADELE AFOLABI",
        church: "Christ Base Assembly",
        address: "10 Shokoya Street Oworonsoki",
        headOffice: "",
        tel: "08034876621",
        email: "oladele.afolabi@ymail.com",
        dOb: "18th June",
        chapter: "Ilasamaja",
        province: "Kosofe",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 12,
        img: Img,
        name: "REV.DR. MOSES BABATUNDE ELEBUTE",
        church: "International Christian Faith Mission",
        address: "14, Aina Close, New Garage, Gbagada, Lagos.",
        headOffice: "",
        tel: "08023159130",
        email: "moseselebute58@gmail.com",
        dOb: "December 4th",
        chapter: "Ilasamaja",
        province: "Kosofe",
        associatePastor: "Pastor (Mrs) Toyin Elebute",
        associatePastorTel: "08053077798",
        associatePastorChapter: "Gbagada",
        associatePastorProvince: "Mainland"
    },
    {
        id: 13,
        img: Img,
        name: "PASTOR DR. BARNABAS OTOIBHI.",
        church: "Temple Rebuilders Ministry.",
        address: "5, Aimasiko Street, Off Afariogun Street, By Charity Bus-Stop, Oshodi, Lagos",
        headOffice: "",
        tel: "08033136167, 08125720158",
        email: "barnytessy@yahoo.com",
        dOb: "15/12",
        chapter: "Oshodi",
        province: "Mushin/Oshodi",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 14,
        img: Img,
        name: "PASTOR DR. BARNABAS OTOIBHI.",
        church: "Temple Rebuilders Ministry.",
        address: "5, Aimasiko Street, Off Afariogun Street, By Charity Bus-Stop, Oshodi, Lagos",
        headOffice: "",
        tel: "08033136167, 08125720158",
        email: "barnytessy@yahoo.com",
        dOb: "15/12",
        chapter: "Oshodi",
        province: "Mushin/Oshodi",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 15,
        img: Img,
        name: "BISHOP ANDY OGBU",
        church: "Dominion Life Centre",
        address: "18, Ebun Otti Street off Frank Lass Bus stop Opp. Lagos State University, Ojo, Badagry Exp.",
        headOffice: "",
        tel: "08033122772, 08120870163",
        email: "dominionlife@gmail.com",
        dOb: "23rd November",
        chapter: "Ojo",
        province: "Ojo",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 16,
        img: Img,
        name: "APOSTLE KEN CHIDUBEM",
        church: "World Lighters Ministries",
        address: "2 Ecwa church road by Alafia bus stop, Coker Orile Iganmu Lagos.",
        headOffice: "",
        tel: "07064691511",
        email: "Kengivethemlight@gmail.com",
        dOb: "18/12",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 17,
        img: Img,
        name: "Pastor David Oluwatosin Oladipupo",
        church: "CommunionHouse",
        address: "3rd Avenue Gowon Estate, Egbeda",
        headOffice: "",
        tel: "08100675902",
        email: "tsn_oladipupo@yahoo.com",
        dOb: "02 August",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 17,
        img: Img,
        name: "Apostle Dr Ameh Joseph Sunday.",
        church: "Restoration Royal Mega Church.",
        address: "15/16, Mohammed Adah Street, Gojere Town, Opposite Ojo Barracks. Ojo Lagos.",
        headOffice: "",
        tel: "08033000758. 08154146579.",
        email: "doctorameh@gmail.com",
        dOb: "",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 18,
        img: Img,
        name: "Rev .Dr Dele Ajayi",
        church: "Chapel of Christ The Light",
        address: "1,CIPM ROAD, CBD, ALAUSA, IKEJA",
        headOffice: "",
        tel: "08023269835",
        email: "oladeleajayi83@gmail.com",
        dOb: "13th January",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 19,
        img: Img,
        name: "Rev .Dr Dele Ajayi",
        church: "Chapel of Christ The Light",
        address: "1,CIPM ROAD, CBD, ALAUSA, IKEJA",
        headOffice: "",
        tel: "08023269835",
        email: "oladeleajayi83@gmail.com",
        dOb: "13th January",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 20,
        img: Img,
        name: "APOSTLE CLEMS PREACHER AKIBOR",
        church: "Jubilee Family Christian Church int'l.",
        address: "40/41 Sule Descendants way, off Church bustop, Okoko Lagos.",
        headOffice: "",
        tel: "08034028313",
        email: "clemspreacher@gmail.com",
        dOb: "February 12th",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 21,
        img: Img,
        name: "Mrs Helen Karika",
        church: "Upper Room Baptist Church",
        address: "Vina Street, Off Badore Road Badore, Ajah, Lekki Lagos.",
        headOffice: "",
        tel: "08023285245",
        email: "helenkarika@yahoo.com",
        dOb: "February 12",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 22,
        img: Img,
        name: "Rev Dr Eric IGHALO",
        church: "Changemakers Africa Youth Empowerment Initiative.",
        address: "142,Oba Akran Road .4th floor,Poatson House.Suite 4.Ikeja.Lagos.",
        headOffice: "",
        tel: "08023291520(main line) 09092218683",
        email: "changemakersafrica@gmail.com, ericandpartners@gmail.com",
        dOb: "19th Dec.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 23,
        img: Img,
        name: "Rev Dr Eric IGHALO",
        church: "Changemakers Africa Youth Empowerment Initiative.",
        address: "142,Oba Akran Road .4th floor,Poatson House.Suite 4.Ikeja.Lagos.",
        headOffice: "",
        tel: "08023291520(main line) 09092218683",
        email: "changemakersafrica@gmail.com, ericandpartners@gmail.com",
        dOb: "19th Dec.",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 24,
        img: Img,
        name: "BISHOP ( DR ) JOY OBERIKO",
        church: "DIVINE SOULS FOR CHRIST CHURCH INTERNATIONAL ( BELIEVERS CATHEDRAL)",
        address: "NO 3 LUQMON AVENUE AHMADIYA LAGOS STATE.",
        headOffice: "",
        tel: "08023428133",
        email: "bishopjoyoberiko2012@gmail.com",
        dOb: "DECEMBER 25TH",
        chapter: "Ojokoro",
        province: "Ifako/Ijaiye",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    {
        id: 25,
        img: Img,
        name: "Pastor Emmanuel Olu Falodun",
        church: "Christ Salvation Victory Mission Int'l",
        address: "63, Falohun Street, Orile Iganmu, Lagos",
        headOffice: "",
        tel: "08033337793",
        email: "powerforexploits@gmail.com",
        dOb: "May 17",
        chapter: "",
        province: "",
        associatePastor: "",
        associatePastorTel: "",
        associatePastorChapter: "",
        associatePastorProvince: ""
    },
    // {
    //     id: 26,
    //     img: Img,
    //     name: "APOSTLE IDONG JAMES",
    //     church: "ALIVE TABERNACLE INT'L",
    //     address: "63, Falohun Street, Orile Iganmu, Lagos",
    //     headOffice: "",
    //     tel: "08033337793",
    //     email: "powerforexploits@gmail.com",
    //     dOb: "May 17",
    //     chapter: "",
    //     province: "",
    //     associatePastor: "",
    //     associatePastorTel: "",
    //     associatePastorChapter: "",
    //     associatePastorProvince: ""
    // },
]